version: '3.7'

services:
  reviews:
    image: jclasley/fec:latest
    # command: sh -c "npm install && npm run start"
    # working_dir: /reviews
    ports:
      - 3001:3001
    # volumes:
    #     - ./:/reviews
    environment:
      - MONGO_URL=mongodb://mongo:27017/etsy
      - PORT=3001
  products:
    image: jwhunt19/product:latest
    ports:
      - 3002:3002
    environment: 
      - MONGO_URL=mongodb://mongo:27017/etsy
      - PORT=3002
  recommended:
    image: pgonz18/recommended2021:latest
    ports:
      - 3003:3003
    environment: 
      - MONGO_URL=mongodb://mongo:27017/recommended
      - PORT=3003
  mongo:
    image: mongo:latest
    volumes:
      - fec:/data/db
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: 'etsy'
      

volumes:
  fec:
